[pytest]
markers =
    RandomPlayer_choose_a_move: "test choose_a_move method in the RandomPlayer class"
    MMNode_expand: "test expand method in the MMNode class"
    MMNode_build_tree: "test build_tree method in the MMNode class"
    MMNode_compute_v: "test compute_v method in the MMNode class"
    MiniMaxPlayer_choose_optimal_move: "test choose_optimal_move method in the MiniMaxPlayer class"
    MiniMaxPlayer_choose_a_move: "test choose_a_move method in the MiniMaxPlayer class"
    MCNode_sample: "test sample method in the MCNode class"
    MCNode_expand: "test expand method in the MCNode class"
    MCNode_backprop: "test backprop method in the MCNode class"
    MCNode_compute_UCB: "test compute_UCB method in the MCNode class"
    MCNode_select_a_child: "test select_a_child method in the MCNode class"
    MCNode_selection: "test selection method in the MCNode class"
    MCNode_build_tree: "test build_tree method in the MCNode class"
    MCTSPlayer_choose_optimal_move: "test choose_optimal_move method in the MCTSPlayer class"
    MCTSPlayer_choose_a_move: "test choose_a_move method in the MCTSPlayer class"
