[pytest]
markers =
    RNN_compute_zt: "test compute_zt method in the RNN class"
    RNN_compute_ht: "test compute_ht method in the RNN class"
    RNN_step: "test step method in the RNN class"
    RNN_compute_z: "test compute_z method in the RNN class"
    RNN_forward: "test forward method in the RNN class"
    RNN_compute_L: "test compute_L method in the RNN class"
    RNN_train: "test train method in the RNN class"
    RNN_predict: "test predict method in the RNN class"
    QK_DotProduct_forward: "test forward method in the QK_DotProduct class"
    QK_ScaleDotProduct_forward: "test forward method in the QK_ScaleDotProduct class"
    QK_SoftMax_forward: "test forward method in the QK_SoftMax class"
    QKV_Attention_forward: "test forward method in the QKV_Attention class"
    AttentionHead_compute_qkv: "test compute_qkv method in the AttentionHead class"
    AttentionHead_forward: "test forward method in the AttentionHead class"
    ResidualLayer_forward: "test forward method in the ResidualLayer class"
